# Generated by Django 4.0.2 on 2022-08-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bote',
            name='eslora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='forma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='manga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='materialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='matricula',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bote',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='propietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='mt_isla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.isla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arte',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
