# Generated by Django 4.0.2 on 2022-08-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bote_eslora_bote_forma_bote_manga_bote_materialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('matricula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('propietario', models.CharField(blank=True, max_length=255, null=True)),
                ('materialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('manga', models.IntegerField(blank=True, null=True)),
                ('eslora', models.IntegerField(blank=True, null=True)),
                ('forma', models.CharField(blank=True, max_length=255, null=True)),
                ('rpa', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mt_bote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bote_id', to='core.bote')),
            ],
            options={
                'verbose_name': 'Bote Historico',
                'verbose_name_plural': 'Bote Historicos',
                'db_table': 'mt_bote_historico',
            },
        ),
    ]
