# Generated by Django 4.0.2 on 2022-08-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botehistorico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botehistorico',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='botehistorico',
            name='updated_at',
        ),
    ]
