# Generated by Django 4.0.2 on 2022-08-07 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_created_at_botehistorico_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botehistorico',
            old_name='fecha_creacion',
            new_name='fecha_cambio',
        ),
        migrations.AddField(
            model_name='bote',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bote',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
