# Generated by Django 4.0.2 on 2022-08-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_fecha_creacion_botehistorico_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botehistorico',
            name='matricula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='botehistorico',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
