# Generated by Django 4.0.2 on 2022-08-07 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_botehistorico_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bote',
            name='user_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bote',
            name='user_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modificador', to=settings.AUTH_USER_MODEL),
        ),
    ]
