# Generated by Django 4.0.2 on 2022-08-07 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bote_user_creador_bote_user_modificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='botehistorico',
            name='user_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
