# Generated by Django 4.0.2 on 2022-08-07 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_botehistorico_user_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botehistorico',
            name='user_responsable',
        ),
        migrations.AddField(
            model_name='botehistorico',
            name='user_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BoteVigenciaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('bote_vigencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.botevigencia')),
                ('mt_bote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bote')),
                ('mt_isla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.isla')),
                ('user_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bote Vigencia Historico',
                'verbose_name_plural': 'Bote Vigencia Historicos',
                'db_table': 'bote_vigencia_historico',
            },
        ),
    ]
